name: Build

on:
  push:
    branches:
      - bleeding-edge
  pull_request:
    branches:
      - bleeding-edge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Get Latest Tag
        id: get_latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --match "build-*" --abbrev=0 || echo "build-0")"

      - name: Calculate Next Tag
        id: calc_next_tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.tag }}"
          next_number=$(( ${latest_tag#build-} + 1 ))
          next_tag="build-${next_number}"
          echo "next_tag=${next_tag}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew desktop:dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.next_tag }}
          release_name: ${{ env.next_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "desktop/build/libs/Mindustry.jar"
          asset_name: "Mindustry.jar"
          asset_content_type: "application/octet-stream"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
